# GitHub Pages configuration
title: "Pousada Bistrô Savacipo"
description: "Um refúgio de tranquilidade na Serra do Cipó"
url: "https://seu-usuario.github.io"
baseurl: "/pousada"

# Exclude from processing
exclude:
  - README.md
  - .gitignore

# Include files
include:
  - .nojekyll
